### ISSUE TITLE
Create a getting-started guide for Claymore

### ISSUE THREAD

**Issue by satendrapalsingh** [fragcolor-xyz/claymore#15]
**Pitch**
As a game creator new to Fragcolor, I want an introductory guide to Claymore tools so that I may be able to start using them in my game projects.

**Acceptance criteria**
A beginner-friendly getting-started guide for Claymore and associated game development tools.

**Additional context**
Document should be hosted at `https://docs.fragcolor.xyz/how-to/use-claymore`.

**Comment by satendrapalsingh** [comment]
@Kryptos-FR Not able to add labels, assignees, epics or start planning poker for this issue

**Comment by satendrapalsingh** [comment]
@Kryptos-FR Issue opened in the wrong repository. Correct issue is [Chainblocks issue #245](https://github.com/fragcolor-xyz/chainblocks/issues/245).

Can we close this issue?

**Comment by Kryptos-FR** [comment]
Yes. You can also move issues from one repo to another.

**Comment by satendrapalsingh** [comment]
> Yes. You can also move issues from one repo to another.

Oh, I didn't realise that. Thanks!
